// <auto-generated />
using System;
using DemoApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApi.Migrations
{
    [DbContext(typeof(WorldContext))]
    partial class WorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DemoApi.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("District")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("char(35)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<int>("Population")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("('0')");

                    b.HasKey("Id");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("DemoApi.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<int?>("Capital")
                        .HasColumnType("int");

                    b.Property<string>("Code2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("Continent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("('Asia')");

                    b.Property<decimal?>("Gnp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("GNP");

                    b.Property<decimal?>("Gnpold")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("GNPOld");

                    b.Property<string>("GovernmentForm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("char(45)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("HeadOfState")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("char(60)")
                        .IsFixedLength();

                    b.Property<short?>("IndepYear")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("LifeExpectancy")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("char(45)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(52)
                        .IsUnicode(false)
                        .HasColumnType("char(52)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<int>("Population")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("('0')");

                    b.Property<string>("Region")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("char(26)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<decimal>("SurfaceArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValueSql("('0.00')");

                    b.HasKey("Code")
                        .HasName("PK__country__A25C5AA6F1A7F7FD");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("DemoApi.Models.Countrylanguage", b =>
                {
                    b.Property<string>("CountryCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasDefaultValueSql("('')")
                        .IsFixedLength();

                    b.Property<string>("IsOfficial")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValueSql("('F')")
                        .IsFixedLength();

                    b.Property<decimal>("Percentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValueSql("('0.0')");

                    b.HasKey("CountryCode", "Language")
                        .HasName("PK__countryl__51A654086D9E467C");

                    b.ToTable("countrylanguage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
